const qs=s=>document.querySelector(s), qsa=s=>[...document.querySelectorAll(s)];
async function api(url,opts={}){const headers={...(opts.headers||{})};if(opts.body && typeof opts.body==='string' && !headers['Content-Type'])headers['Content-Type']='application/json';const r=await fetch(url,{...opts,headers});if(r.status===401){location.href='/login';throw new Error('Authentication required')}const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Request failed');return j}
async function post(url,data){return api(url,{method:'POST',body:JSON.stringify(data)})}
let data=null,currentConv=null,localizationBound=false;
const days=['sun','mon','tue','wed','thu','fri','sat'];
function esc(s=''){return String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}
function money(v,currency){const n=Number(v||0);try{return new Intl.NumberFormat(undefined,{style:'currency',currency:currency||'USD',maximumFractionDigits:0}).format(n)}catch{return `${currency||''} ${n.toFixed(0)}`}}
function niceStatus(s=''){return String(s).replaceAll('_',' ').replace(/\b\w/g,x=>x.toUpperCase())}
function page(name){qsa('[id^="page-"]').forEach(x=>x.classList.add('hidden'));qs('#page-'+name).classList.remove('hidden');qsa('.side-nav button[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===name));if(innerWidth<901)qs('#sidebar').classList.remove('open');if(name==='conversations')loadConversations();if(name==='appointments')loadAppointments();if(name==='recovery')loadRecovery();}
qsa('.side-nav button[data-page]').forEach(b=>b.onclick=()=>page(b.dataset.page));qsa('[data-go]').forEach(b=>b.onclick=()=>page(b.dataset.go));qs('#menu').onclick=()=>qs('#sidebar').classList.toggle('open');
qs('#logout').onclick=async()=>{const wasDemo=!!data?.business?.is_demo;await post('/api/auth/logout',{});location.href=wasDemo?'/':'/login'};

function render(){
  const b=data.business,c=data.config,w=data.whatsapp,a=data.automation||{};const cur=b.currency||'USD';
  qs('#clinicTop').textContent=b.name;qs('#planTop').textContent=b.is_demo?'INTERACTIVE DEMO • temporary sandbox':`${b.plan.toUpperCase()} • ${b.status}`;qs('#trialBadge').textContent=b.is_demo?'Live demo':(b.status==='trial'?'Trial active':b.status);qs('#demoBanner').classList.toggle('hidden',!b.is_demo);qs('#logout').textContent=b.is_demo?'Exit demo':'Log out';qs('#aiStatus').textContent=c.auto_reply?'AI active':'AI paused';qs('#aiStatus').className='status'+(c.auto_reply?'':' warn');
  qs('#statConv').textContent=data.counts.conversations;qs('#statApt').textContent=data.counts.appointmentsToday;qs('#statLeads').textContent=data.counts.leads;qs('#statRecovered').textContent=money(a.totalRecoveredValue||0,cur);qs('#overviewRecoveredLeads').textContent=a.lostLead?.recovered||0;qs('#overviewRefilled').textContent=a.cancellation?.filled||0;qs('#overviewVoice').textContent=a.voiceNotes||0;
  qs('#recentConvs').innerHTML=data.recentConversations.length?data.recentConversations.map(x=>`<div style="padding:10px 0;border-bottom:1px solid var(--line)"><strong>${x.last_message_type==='voice'?'🎤 ':''}${esc(x.customer_name||x.customer_phone)}</strong><div style="font-size:12px;color:var(--muted)">${esc(x.last_message||'')}</div></div>`).join(''):'<p style="color:var(--muted)">No conversations yet.</p>';
  qs('#recentApts').innerHTML=data.appointments.length?data.appointments.map(x=>`<div style="padding:10px 0;border-bottom:1px solid var(--line)"><strong>${esc(x.service_name)}</strong><div style="font-size:12px;color:var(--muted)">${esc(x.customer_name||x.customer_phone)} • ${x.date} ${x.time} • ${niceStatus(x.source)}</div></div>`).join(''):'<p style="color:var(--muted)">No appointments yet.</p>';
  qs('#bName').value=b.name||'';const dial=b.phone_country_code||'';const full=String(b.phone||'');qs('#bPhone').value=dial&&full.startsWith(dial)?full.slice(dial.length):full;qs('#bAddress').value=b.address||'';
  if(!localizationBound){ClinicLocalization.bind({country:qs('#bCountry'),dial:qs('#bPhoneCode'),currency:qs('#bCurrency'),timezone:qs('#bTimezone'),initialCountry:b.country_code||'OTHER',initialDial:dial,initialCurrency:b.currency||'USD',initialTimezone:b.timezone||'UTC'});localizationBound=true}else{qs('#bCountry').value=ClinicLocalization.byCode[b.country_code]?b.country_code:'OTHER';qs('#bPhoneCode').value=dial;qs('#bTimezone').value=b.timezone||'';qs('#bCurrency').value=b.currency||'';}
  qs('#aiName').value=c.ai_name||'';qs('#aiGreeting').value=c.greeting||'';qs('#aiTone').value=c.tone||'';qs('#aiLanguages').value=(c.languages||[]).join(', ');qs('#autoReply').checked=!!c.auto_reply;qs('#bookingEnabled').checked=!!c.booking_enabled;qs('#safetyHandoff').checked=!!c.safety_handoff;
  qs('#recoveryEnabled').checked=!!c.lost_lead_recovery;qs('#recoveryDelay').value=String(c.recovery_delay_minutes||120);qs('#cancelAutoFill').checked=!!c.cancellation_autofill;qs('#cancelMaxOffers').value=String(c.cancellation_max_offers||5);qs('#voiceNotesEnabled').checked=!!c.voice_notes_enabled;
  qs('#hours').innerHTML=days.map(d=>{const r=c.opening_hours?.[d]||['',''];return `<div style="display:grid;grid-template-columns:70px 1fr 1fr;gap:8px;margin:8px 0;align-items:center"><strong style="text-transform:capitalize">${d}</strong><input data-day="${d}" data-i="0" value="${esc(r?.[0]||'')}" placeholder="09:00"><input data-day="${d}" data-i="1" value="${esc(r?.[1]||'')}" placeholder="18:00"></div>`}).join('');
  qs('#faqs').value=(c.faqs||[]).map(x=>`${x.q||x.question||''} | ${x.a||x.answer||''}`).join('\n');renderServices();
  qs('#waStatus').innerHTML=b.is_demo?`<span class="status warn">Demo sandbox</span><h3>WhatsApp connection is disabled in the public demo</h3><p style="color:var(--muted)">The chat and booking workflow is fully testable here. Create a clinic workspace to connect a real WhatsApp Business number.</p><a class="btn brand small" href="/signup">Create clinic workspace</a>`:(w?.status==='connected'?`<span class="status">Connected</span><h3 style="margin-bottom:5px">${esc(w.display_number||'WhatsApp number')}</h3><p style="color:var(--muted)">Phone Number ID: ${esc(w.phone_number_id||'')}</p><p class="kpi-note">Voice-note reception and revenue-recovery messages use this same clinic number.</p>`:`<span class="status warn">Not connected</span><h3>WhatsApp onboarding required</h3><p style="color:var(--muted)">Contact the ClinicChatDesk platform team to connect your business number.</p>`);
}
function renderServices(){const cur=data?.business?.currency||'USD';qs('#services').innerHTML=(data.services||[]).map(s=>`<div class="service-row"><input data-s="${s.id}" data-k="name" value="${esc(s.name)}"><input data-s="${s.id}" data-k="price" type="number" value="${s.price}"><span class="currency-chip">${esc(cur)}</span><input data-s="${s.id}" data-k="duration_minutes" type="number" value="${s.duration_minutes}"><button class="btn ghost small save-service" data-id="${s.id}">Save</button></div>`).join('')||'<p style="color:var(--muted)">No services yet.</p>';qsa('.save-service').forEach(b=>b.onclick=async()=>{const id=b.dataset.id,obj={};qsa(`[data-s="${id}"]`).forEach(i=>obj[i.dataset.k]=i.type==='number'?Number(i.value):i.value);await post('/api/clinic/services/'+id,obj);await load();});}
qs('#addService').onclick=async()=>{const name=prompt('Service name');if(!name)return;const price=Number(prompt('Price')||0);const duration_minutes=Number(prompt('Duration in minutes')||30);await post('/api/clinic/services',{name,price,duration_minutes});await load();page('knowledge')};
qs('#saveBusiness').onclick=async()=>{const opening_hours={};for(const d of days){const vals=qsa(`[data-day="${d}"]`).map(i=>i.value.trim());opening_hours[d]=vals[0]&&vals[1]?vals:null}const faqs=qs('#faqs').value.split('\n').map(l=>l.split('|')).filter(x=>x[0]?.trim()&&x[1]?.trim()).map(([q,...a])=>({q:q.trim(),a:a.join('|').trim()}));await post('/api/clinic/business',{name:qs('#bName').value,country_code:qs('#bCountry').value==='OTHER'?'ZZ':qs('#bCountry').value,phone_country_code:qs('#bPhoneCode').value,phone:qs('#bPhone').value,address:qs('#bAddress').value,timezone:qs('#bTimezone').value,currency:qs('#bCurrency').value.toUpperCase()});await post('/api/clinic/config',{opening_hours,faqs});await load();alert('Business knowledge saved.')};
qs('#saveAI').onclick=async()=>{await post('/api/clinic/config',{ai_name:qs('#aiName').value,greeting:qs('#aiGreeting').value,tone:qs('#aiTone').value,languages:qs('#aiLanguages').value.split(',').map(x=>x.trim()).filter(Boolean),auto_reply:qs('#autoReply').checked,booking_enabled:qs('#bookingEnabled').checked,safety_handoff:qs('#safetyHandoff').checked});await load();alert('AI settings saved.')};
qs('#saveRecovery').onclick=async()=>{await post('/api/clinic/config',{lost_lead_recovery:qs('#recoveryEnabled').checked,recovery_delay_minutes:Number(qs('#recoveryDelay').value),cancellation_autofill:qs('#cancelAutoFill').checked,cancellation_max_offers:Number(qs('#cancelMaxOffers').value),voice_notes_enabled:qs('#voiceNotesEnabled').checked});await load();await loadRecovery();alert('Revenue Recovery settings saved.')};
qs('#runAutomation').onclick=async()=>{qs('#runAutomation').disabled=true;try{const r=await post('/api/clinic/automation/run',{});await load();await loadRecovery();alert(r.results?.length?`Automation checked ${r.results.length} due action(s).`:'Automation checked — nothing is due right now.')}catch(e){alert(e.message)}finally{qs('#runAutomation').disabled=false}};

async function loadConversations(){const r=await api('/api/clinic/conversations');qs('#convList').innerHTML=r.conversations.map(c=>`<div class="conv" data-id="${c.id}" data-human="${c.human_handoff}"><strong>${c.last_message_type==='voice'?'🎤 ':''}${esc(c.customer_name||c.customer_phone)}</strong><small>${esc(c.last_message||'')}</small></div>`).join('')||'<div style="padding:18px;color:var(--muted)">No conversations.</div>';qsa('.conv').forEach(x=>x.onclick=()=>openConv(x.dataset.id,x.dataset.human==='1',x.querySelector('strong').textContent));}
async function openConv(id,human,name){currentConv={id,human};qs('#convTitle').textContent=name;qs('#handoffBtn').classList.remove('hidden');qs('#handoffBtn').textContent=human?'Return to AI':'Take over';const r=await api(`/api/clinic/conversations/${id}/messages`);qs('#messages').innerHTML=r.messages.map(m=>`<div class="msg ${m.role==='assistant'?'assistant':'user'}">${m.message_type==='voice'?'<div class="voice-chip">🎤 Voice note transcript</div>':''}${esc(m.text)}</div>`).join('');qs('#messages').scrollTop=qs('#messages').scrollHeight;}
qs('#handoffBtn').onclick=async()=>{if(!currentConv)return;await post(`/api/clinic/conversations/${currentConv.id}/handoff`,{enabled:!currentConv.human});currentConv.human=!currentConv.human;qs('#handoffBtn').textContent=currentConv.human?'Return to AI':'Take over';await loadConversations()};

async function loadAppointments(){const r=await api('/api/clinic/appointments');qs('#aptTable').innerHTML=r.appointments.map(a=>`<tr><td>${a.date}</td><td>${a.time}</td><td>${esc(a.customer_name||a.customer_phone)}</td><td>${esc(a.service_name)}</td><td><span class="source-pill ${esc(a.source)}">${niceStatus(a.source)}</span></td><td><span class="status ${a.status==='cancelled'?'danger':''}">${niceStatus(a.status)}</span></td><td>${a.status==='confirmed'?`<button class="btn ghost small cancel-apt" data-id="${a.id}">Cancel + refill</button>`:''}</td></tr>`).join('')||'<tr><td colspan="7">No appointments yet.</td></tr>';qsa('.cancel-apt').forEach(b=>b.onclick=async()=>{if(!confirm('Cancel this appointment and start Cancellation Auto-Fill?'))return;const reason=prompt('Cancellation reason (optional)','Clinic cancellation')||'Clinic cancellation';try{const r=await post(`/api/clinic/appointments/${b.dataset.id}/cancel`,{reason});alert(r.opportunity?'Appointment cancelled. Auto-fill candidate search started.':'Appointment cancelled. Auto-fill is disabled or no workflow was created.');await load();await loadAppointments();await loadRecovery();}catch(e){alert(e.message)}})}

async function loadRecovery(){const r=await api('/api/clinic/revenue-recovery');const s=r.stats,cur=data?.business?.currency||'USD';qs('#rrRecovered').textContent=s.lostLead.recovered;qs('#rrRecoveryValue').textContent=money(s.lostLead.recoveredValue,cur)+' recovered';qs('#rrRefilled').textContent=s.cancellation.filled;qs('#rrCancelValue').textContent=money(s.cancellation.recoveredValue,cur)+' recovered';qs('#rrPending').textContent=s.lostLead.pending;qs('#rrVoice').textContent=s.voiceNotes;qs('#recoveryRows').innerHTML=r.recoveryCases.map(x=>`<tr><td>${esc(x.customer_name||x.customer_phone)}</td><td>${esc(x.service_name||'General enquiry')}</td><td><span class="status ${x.status==='template_required'?'warn':''}">${niceStatus(x.status)}</span></td><td>${money(x.estimated_value||0,cur)}</td><td>${x.last_sent_at?new Date(x.last_sent_at).toLocaleString():new Date(x.scheduled_at).toLocaleString()}</td></tr>`).join('')||'<tr><td colspan="5">No recovery cases yet. They appear after a high-intent patient leaves without booking.</td></tr>';qs('#cancelRows').innerHTML=r.cancellations.map(x=>`<tr><td>${x.date}<br><small>${x.time}</small></td><td>${esc(x.service_name)}</td><td><span class="status ${x.status==='template_required'?'warn':''}">${niceStatus(x.status)}</span></td><td>${x.offer_count||0}</td><td>${money(x.recovered_value||0,cur)}</td></tr>`).join('')||'<tr><td colspan="5">No cancelled-slot opportunities yet.</td></tr>'}

async function sendTest(text){if(!text.trim())return;const box=qs('#testChat');box.insertAdjacentHTML('beforeend',`<div class="msg user">${esc(text)}</div>`);qs('#testInput').value='';try{const r=await post('/api/clinic/test-chat',{phone:`${data?.business?.phone_country_code||'+1'}5550000000`,name:'Demo Patient',message:text});if(r.reply)box.insertAdjacentHTML('beforeend',`<div class="msg assistant">${esc(r.reply)}</div>`);box.scrollTop=box.scrollHeight;await load()}catch(e){box.insertAdjacentHTML('beforeend',`<div class="msg assistant">${esc(e.message)}</div>`)} }
qs('#testSend').onclick=()=>sendTest(qs('#testInput').value);qs('#testInput').addEventListener('keydown',e=>{if(e.key==='Enter')sendTest(e.target.value)});qsa('.quick').forEach(b=>b.onclick=()=>sendTest(b.textContent));
qs('#voiceSend').onclick=async()=>{const f=qs('#voiceFile').files?.[0];if(!f){alert('Choose an audio file first.');return}qs('#voiceSend').disabled=true;qs('#voiceResult').textContent='Transcribing and processing…';try{const r=await api(`/api/clinic/test-voice?filename=${encodeURIComponent(f.name)}`,{method:'POST',headers:{'Content-Type':f.type||'audio/ogg'},body:f});qs('#voiceResult').innerHTML=`<strong>Transcript:</strong> ${esc(r.transcript)}<br><strong>AI:</strong> ${esc(r.reply||'No automatic reply — human takeover or AI pause may be active.')}`;const box=qs('#testChat');box.insertAdjacentHTML('beforeend',`<div class="msg user"><div class="voice-chip">🎤 Voice note transcript</div>${esc(r.transcript)}</div>`);if(r.reply)box.insertAdjacentHTML('beforeend',`<div class="msg assistant">${esc(r.reply)}</div>`);await load();}catch(e){qs('#voiceResult').textContent=e.message}finally{qs('#voiceSend').disabled=false}};

async function load(){data=await api('/api/clinic/dashboard');render()}load();
