import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import { DatabaseSync } from 'node:sqlite';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'clinicchatdesk-smoke-'));process.env.DATA_DIR=dir;process.env.SUPER_ADMIN_EMAIL='smoke-owner@example.com';process.env.SUPER_ADMIN_PASSWORD='SmokePassword123!';process.env.DEMO_MODE='true';
const db=await import('./db.mjs');db.initDb();
const c=db.createClinicWithOwner({clinicName:'Smoke Dental',ownerName:'Owner',email:'smoke-clinic@example.com',password:'Password123!'});
const hours={sun:['09:00','18:00'],mon:['09:00','18:00'],tue:['09:00','18:00'],wed:['09:00','18:00'],thu:['09:00','18:00'],fri:['09:00','18:00'],sat:['09:00','18:00']};db.updateConfig(c.businessId,{opening_hours:hours,recovery_delay_minutes:15,lost_lead_recovery:true,cancellation_autofill:true,voice_notes_enabled:true});db.createService(c.businessId,{name:'Dental Cleaning',price:200,duration_minutes:30});
const bundle=db.getBusinessBundle(c.businessId);if(bundle.business.name!=='Smoke Dental'||bundle.business.currency!=='USD'||bundle.business.timezone!=='UTC'||bundle.services.length!==1||bundle.services[0].currency!=='USD')throw new Error('Base clinic/localization smoke failed');

// Lost-lead recovery detection.
const lost=db.getOrCreateConversation(c.businessId,'+10001','Lost Lead','whatsapp');db.saveMessage(lost.conversation.id,'user','How much is Dental Cleaning?');db.upsertLead(c.businessId,lost.customer.id,'Dental Cleaning');
const raw=new DatabaseSync(db.dbInfo().dbPath);const old=new Date(Date.now()-2*60*60*1000).toISOString();raw.prepare("UPDATE messages SET created_at=? WHERE conversation_id=? AND role='user'").run(old,lost.conversation.id);raw.close();
const queued=db.queueLostLeadRecoveries(c.businessId);if(queued<1||!db.listRecoveryCases(c.businessId).some(x=>x.customer_id===lost.customer.id&&x.status==='queued'))throw new Error('Lost Lead Recovery smoke failed');

// Cancellation auto-fill: one patient is interested, another cancels the slot.
const candidate=db.getOrCreateConversation(c.businessId,'+10002','Waitlist Patient','whatsapp');db.saveMessage(candidate.conversation.id,'user','I want Dental Cleaning');db.upsertLead(c.businessId,candidate.customer.id,'Dental Cleaning');
const booked=db.getOrCreateConversation(c.businessId,'+10003','Booked Patient','whatsapp');const date=new Date(Date.now()+86400000).toISOString().slice(0,10);const apt=db.createAppointment(c.businessId,booked.customer.id,'Dental Cleaning',date,'10:00');const cancelled=db.cancelAppointment(c.businessId,apt.id,'Smoke cancellation');if(!cancelled.opportunity)throw new Error('Cancellation opportunity not created');
const next=db.nextCancellationOffers(c.businessId,5)[0];if(!next||next.customer_id!==candidate.customer.id)throw new Error('Cancellation candidate queue failed');db.markCancellationOfferSent(next.id,20);const refilled=db.acceptCancellationOffer(c.businessId,next.id,candidate.customer.id);if(refilled.source!=='cancellation_autofill')throw new Error('Cancellation auto-fill source failed');

// Voice-note audit path (actual OpenAI transcription requires a live API key).
const voice=db.getOrCreateConversation(c.businessId,'+10004','Voice Patient','whatsapp');db.saveMessage(voice.conversation.id,'user','I need an appointment',null,{message_type:'voice',transcription_status:'completed'});const stats=db.automationStats(c.businessId);if(stats.cancellation.filled!==1||stats.cancellation.recoveredValue!==200||stats.voiceNotes!==1)throw new Error('Revenue/voice stats smoke failed');
const demo=db.createDemoClinic({countryCode:'PK',phoneCountryCode:'+92',currency:'PKR',timezone:'Asia/Karachi'});const demoDash=db.dashboard(demo.businessId);if(!demoDash.business.is_demo||demoDash.business.currency!=='PKR'||demoDash.services.some(x=>x.currency!=='PKR')||demoDash.automation.totalRecoveredValue<=0)throw new Error('Live demo/localization smoke failed');db.updateBusiness(demo.businessId,{currency:'AED',phone_country_code:'+971',country_code:'AE'});if(db.getBusinessBundle(demo.businessId).services.some(x=>x.currency!=='AED'))throw new Error('Clinic-level currency sync failed');console.log('ClinicChatDesk v2.4 smoke test passed: localization, live demo, Revenue Recovery, Cancellation Auto-Fill, and Voice-Note tracking.');fs.rmSync(dir,{recursive:true,force:true});
